##### Logging Configuration ####
logging:
  level:
    org.springframework.security: DEBUG
debug: true

#### SERVER ####
server:
  port: 8081

#### Spring config #####
spring:
  application:
    name: NewsAPI
  jpa:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
