services:

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_SPRING_USER}
      - MYSQL_PASSWORD=${DB_SPRING_PASSWD}
      - MYSQL_DATABASE=news
    volumes:
      - persist-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - backend

  server:
    build: NewsAPI
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/news
      - SPRING_DATASOURCE_USERNAME=${DB_SPRING_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_SPRING_PASSWD}
    volumes:
      - persist-backend:/home/spring/images
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - backend

  classifier:
    build: NewsAI/Classifier
    environment:
      - HF_TOKEN=${CLASSIFIER_TOKEN}
      - HF_API=${CLASSIFIER_API}
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      backend:
        aliases:
          - ai.classifier

  corrector:
    build: NewsAI/Corrector
    environment:
      - HF_TOKEN=${CORRECTOR_TOKEN}
      - HF_API=${CORRECTOR_API}
      - HF_MODEL=${CORRECTOR_MODEL}
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      backend:
        aliases:
          - ai.corrector

  reverse-proxy:
    build: NewsReverseProxy
    ports:
      - 8080:80
    depends_on:
      server: { condition: service_healthy }
    restart: always
    networks:
      - backend

volumes:
  persist-db:
  persist-backend:

networks:
  backend:
    driver: bridge
