name: newsweb
description: "newsweb"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  universal_html: ^2.2.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.7.7+1
  cached_network_image: ^3.4.1
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true